### ISSUE TITLE
ver 0.8.x is calling node fetch api in browser

### ISSUE THREAD

**Issue by arjunadotfusion** [agility/agility-content-fetch-js-sdk#44]
Hey there

something done in the master branch is breaking unpkg functionality as mentioned in docs. from the console errors it seems to be failing becase `process` is not found. That indicates an issue with the api thinking it is in a node env not the browser env.

**Comment by alitahir360** [comment]
Hey Arjuna, Yes that is a bug.  will be fixed shortly.

**Comment by alitahir360** [comment]
Fixed in 0.8.1.  Please update the npm package.
